### ISSUE TITLE
Support CircleCI.

### ISSUE THREAD

**Issue by ZucchiniZe** [jollygoodcode/dasherize#9]
My project(s) uses circle ci for our tests and was I was wondering if you could support that soon.

**Comment by winston** [comment]
I'll look into it. :)

## 

Cheers,
Winston

_Founder / Principal Engineering Consultant_

_Jolly Good CodeT: @winstonywP: +65 9437 1845_

**Comment by ZucchiniZe** [comment]
Thanks.
